apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: language-platform

resources:
  - namespace.yaml
  - auth/
  - users/
  - courses/

commonLabels:
  app.kubernetes.io/part-of: language-platform
